name: seatu_ersih
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  get: any
  get_storage: ^2.1.1
  google_fonts: any
  http: ^1.2.1
  lottie: ^3.1.2
  path_provider: any
  shared_preferences: ^2.0.9
  sqflite: ^2.3.3+1
  image_picker:
  intl: any
  flutter_rating_bar:
  dropdown_button2:
  shimmer: 
  firebase_core:
  firebase_messaging: 
  webview_flutter: 
  url_launcher: ^6.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/cleaning.png
